"""ORM base classes shared by every module (ADR-0003).

* :class:`Base`: one ``MetaData`` for schema ``app`` with deterministic constraint names.
* :class:`TenantScoped`: ``tenant_id`` + uuidv7 ``id`` + ``UNIQUE (tenant_id, id)`` (the target of composite FKs).
* :class:`Audited`: ``created_at``/``updated_at`` and the acting user ids.
* :class:`Versioned`: ``version`` for optimistic concurrency (``If-Match``).

Tables are created by hand-written Alembic migrations that also add the RLS policy (see :mod:`app.core.rls`);
the catalog guard test fails if a table in ``app`` is neither tenant-scoped nor allow-listed as global.
"""

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any, ClassVar

from sqlalchemy import (
    DateTime,
    MetaData,
    Numeric,
    String,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

APP_SCHEMA = "app"

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# Money columns: NUMERIC(20,4) (CLAUDE.md rule 2).
MoneyColumn = Numeric(20, 4, asdecimal=True)
# Rates as fractions (0.16 = 16%).
RateColumn = Numeric(12, 8, asdecimal=True)


class Base(DeclarativeBase):
    metadata = MetaData(schema=APP_SCHEMA, naming_convention=NAMING_CONVENTION)
    type_annotation_map: ClassVar[dict[Any, Any]] = {
        uuid.UUID: UUID(as_uuid=True),
        datetime: DateTime(timezone=True),
        Decimal: MoneyColumn,
        str: String(),
    }


def uuidv7_pk() -> Mapped[uuid.UUID]:
    """Time-ordered primary key generated by Postgres 18 (``uuidv7()``)."""
    return mapped_column(primary_key=True, server_default=text("uuidv7()"))


class TenantScoped:
    """Mixin for tenant-owned tables. Pair with ``tenant_rls_sql`` in the migration."""

    id: Mapped[uuid.UUID] = uuidv7_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(index=False)

    @declared_attr.directive
    @classmethod
    def __table_args__(cls) -> tuple[Any, ...]:
        # ``UNIQUE (tenant_id, id)`` lets child tables declare composite FKs that cannot cross tenants.
        return (UniqueConstraint("tenant_id", "id"),)


class Audited:
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())
    created_by: Mapped[str | None] = mapped_column(default=None)
    updated_by: Mapped[str | None] = mapped_column(default=None)


class Versioned:
    """Optimistic concurrency.

    The API compares ``If-Match`` with ``version`` (see :mod:`app.core.concurrency`); SQLAlchemy then increments
    it and adds ``WHERE version = <old>`` to the UPDATE, so a concurrent writer that slipped in between raises
    ``StaleDataError`` instead of being silently overwritten.
    """

    version: Mapped[int] = mapped_column(server_default=text("1"))

    @declared_attr.directive
    @classmethod
    def __mapper_args__(cls) -> dict[str, Any]:
        return {"version_id_col": cls.__table__.c.version}  # type: ignore[attr-defined]
